import mongoose from "mongoose";

const projectSchema = new mongoose.Schema(
  {
    userId: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true, index: true },
    name: { type: String, required: true, trim: true },
    technologies: { type: [String], default: [] },
    architecture: { type: String, default: "" },
    description: { type: String, required: true },
    role: { type: String, default: "" },
    achievements: { type: [String], default: [] },
    complexity: { type: String, enum: ["low", "medium", "high"], default: "medium" },
    relevance: { type: Number, min: 0, max: 100, default: 50 },
    
    // Project Interview Kit generated by AI
    interviewKit: {
      type: [{
        question: String,
        category: String,
        difficulty: String
      }],
      default: []
    }
  },
  { timestamps: true }
);

export const Project = mongoose.model("Project", projectSchema);
