import { ContextSources } from "./userContextService.js";

/**
 * EvidenceBuilder
 * Takes a context plan and executes the required data fetching concurrently.
 * 
 * @param {Object} plan - The plan generated by ContextPlanner
 * @param {string} userId - The user ID
 * @returns {Promise<Object>} The structured context data budget
 */
export async function buildEvidence(plan, userId) {
  const contextData = {};
  const promises = [];

  // We always fetch the profile name at minimum so the AI knows who it's talking to
  if (!plan.sources.includes("profile")) {
    plan.sources.push("profile");
  }

  for (const source of plan.sources) {
    if (ContextSources[source]) {
      // If the source requires an entity ID (like a specific application)
      if (source === "application" || source === "matchResult" || source === "getInterviewReport") {
        // Find if the planner resolved an entity for this type
        // This is a naive matching; can be improved based on entity types
        const relatedEntity = plan.entities.find(e => e.type === source || e.type === "job");
        if (relatedEntity && relatedEntity.id) {
          promises.push(
            ContextSources[source](userId, relatedEntity.id).then(data => {
              if (data) contextData[source] = data;
            }).catch(err => {
              console.warn(`[EvidenceBuilder] Failed to fetch ${source} for entity ${relatedEntity.id}:`, err.message);
            })
          );
        } else {
           // Fallback: if no specific entity was resolved but it was requested, 
           // maybe we just skip or fetch the latest. For now, skip to prevent crashing.
           console.warn(`[EvidenceBuilder] Source ${source} requested but no entity ID resolved.`);
        }
      } else {
        // Standard parameterless fetch (just userId)
        promises.push(
          ContextSources[source](userId).then(data => {
            if (data) contextData[source] = data;
          }).catch(err => {
            console.warn(`[EvidenceBuilder] Failed to fetch ${source}:`, err.message);
          })
        );
      }
    } else {
      console.warn(`[EvidenceBuilder] Unknown context source requested: ${source}`);
    }
  }

  await Promise.all(promises);

  return contextData;
}
